package com.alibaba.csp.sentinel.dashboard.biz.entity;

import java.io.Serializable;
import java.util.Date;

public class DegradeRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String app;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.limit_app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String limitApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.resource
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.grade
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.count
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Double count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.slow_ratio_threshold
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Double slowRatioThreshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.time_window
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Integer timeWindow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.min_request_amount
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Integer minRequestAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.stat_interval_ms
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Integer statIntervalMs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.degrade_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String degradeRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.oper_id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.creator
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.gmt_create
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degrade_rule.gmt_modified
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table degrade_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.id
     *
     * @return the value of degrade_rule.id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.id
     *
     * @param id the value for degrade_rule.id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.app
     *
     * @return the value of degrade_rule.app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.app
     *
     * @param app the value for degrade_rule.app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setApp(String app) {
        this.app = app == null ? null : app.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.limit_app
     *
     * @return the value of degrade_rule.limit_app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getLimitApp() {
        return limitApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.limit_app
     *
     * @param limitApp the value for degrade_rule.limit_app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setLimitApp(String limitApp) {
        this.limitApp = limitApp == null ? null : limitApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.resource
     *
     * @return the value of degrade_rule.resource
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.resource
     *
     * @param resource the value for degrade_rule.resource
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.grade
     *
     * @return the value of degrade_rule.grade
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.grade
     *
     * @param grade the value for degrade_rule.grade
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.count
     *
     * @return the value of degrade_rule.count
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Double getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.count
     *
     * @param count the value for degrade_rule.count
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setCount(Double count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.slow_ratio_threshold
     *
     * @return the value of degrade_rule.slow_ratio_threshold
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Double getSlowRatioThreshold() {
        return slowRatioThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.slow_ratio_threshold
     *
     * @param slowRatioThreshold the value for degrade_rule.slow_ratio_threshold
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setSlowRatioThreshold(Double slowRatioThreshold) {
        this.slowRatioThreshold = slowRatioThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.time_window
     *
     * @return the value of degrade_rule.time_window
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Integer getTimeWindow() {
        return timeWindow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.time_window
     *
     * @param timeWindow the value for degrade_rule.time_window
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setTimeWindow(Integer timeWindow) {
        this.timeWindow = timeWindow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.min_request_amount
     *
     * @return the value of degrade_rule.min_request_amount
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Integer getMinRequestAmount() {
        return minRequestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.min_request_amount
     *
     * @param minRequestAmount the value for degrade_rule.min_request_amount
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setMinRequestAmount(Integer minRequestAmount) {
        this.minRequestAmount = minRequestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.stat_interval_ms
     *
     * @return the value of degrade_rule.stat_interval_ms
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Integer getStatIntervalMs() {
        return statIntervalMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.stat_interval_ms
     *
     * @param statIntervalMs the value for degrade_rule.stat_interval_ms
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setStatIntervalMs(Integer statIntervalMs) {
        this.statIntervalMs = statIntervalMs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.degrade_rule
     *
     * @return the value of degrade_rule.degrade_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getDegradeRule() {
        return degradeRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.degrade_rule
     *
     * @param degradeRule the value for degrade_rule.degrade_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setDegradeRule(String degradeRule) {
        this.degradeRule = degradeRule == null ? null : degradeRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.oper_id
     *
     * @return the value of degrade_rule.oper_id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.oper_id
     *
     * @param operId the value for degrade_rule.oper_id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.creator
     *
     * @return the value of degrade_rule.creator
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.creator
     *
     * @param creator the value for degrade_rule.creator
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.gmt_create
     *
     * @return the value of degrade_rule.gmt_create
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.gmt_create
     *
     * @param gmtCreate the value for degrade_rule.gmt_create
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degrade_rule.gmt_modified
     *
     * @return the value of degrade_rule.gmt_modified
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degrade_rule.gmt_modified
     *
     * @param gmtModified the value for degrade_rule.gmt_modified
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}