package com.alibaba.csp.sentinel.dashboard.biz.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FlowRuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public FlowRuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppIsNull() {
            addCriterion("app is null");
            return (Criteria) this;
        }

        public Criteria andAppIsNotNull() {
            addCriterion("app is not null");
            return (Criteria) this;
        }

        public Criteria andAppEqualTo(String value) {
            addCriterion("app =", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotEqualTo(String value) {
            addCriterion("app <>", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppGreaterThan(String value) {
            addCriterion("app >", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppGreaterThanOrEqualTo(String value) {
            addCriterion("app >=", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppLessThan(String value) {
            addCriterion("app <", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppLessThanOrEqualTo(String value) {
            addCriterion("app <=", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppLike(String value) {
            addCriterion("app like", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotLike(String value) {
            addCriterion("app not like", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppIn(List<String> values) {
            addCriterion("app in", values, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotIn(List<String> values) {
            addCriterion("app not in", values, "app");
            return (Criteria) this;
        }

        public Criteria andAppBetween(String value1, String value2) {
            addCriterion("app between", value1, value2, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotBetween(String value1, String value2) {
            addCriterion("app not between", value1, value2, "app");
            return (Criteria) this;
        }

        public Criteria andLimitAppIsNull() {
            addCriterion("limit_app is null");
            return (Criteria) this;
        }

        public Criteria andLimitAppIsNotNull() {
            addCriterion("limit_app is not null");
            return (Criteria) this;
        }

        public Criteria andLimitAppEqualTo(String value) {
            addCriterion("limit_app =", value, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppNotEqualTo(String value) {
            addCriterion("limit_app <>", value, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppGreaterThan(String value) {
            addCriterion("limit_app >", value, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppGreaterThanOrEqualTo(String value) {
            addCriterion("limit_app >=", value, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppLessThan(String value) {
            addCriterion("limit_app <", value, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppLessThanOrEqualTo(String value) {
            addCriterion("limit_app <=", value, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppLike(String value) {
            addCriterion("limit_app like", value, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppNotLike(String value) {
            addCriterion("limit_app not like", value, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppIn(List<String> values) {
            addCriterion("limit_app in", values, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppNotIn(List<String> values) {
            addCriterion("limit_app not in", values, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppBetween(String value1, String value2) {
            addCriterion("limit_app between", value1, value2, "limitApp");
            return (Criteria) this;
        }

        public Criteria andLimitAppNotBetween(String value1, String value2) {
            addCriterion("limit_app not between", value1, value2, "limitApp");
            return (Criteria) this;
        }

        public Criteria andResourceIsNull() {
            addCriterion("resource is null");
            return (Criteria) this;
        }

        public Criteria andResourceIsNotNull() {
            addCriterion("resource is not null");
            return (Criteria) this;
        }

        public Criteria andResourceEqualTo(String value) {
            addCriterion("resource =", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotEqualTo(String value) {
            addCriterion("resource <>", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceGreaterThan(String value) {
            addCriterion("resource >", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceGreaterThanOrEqualTo(String value) {
            addCriterion("resource >=", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceLessThan(String value) {
            addCriterion("resource <", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceLessThanOrEqualTo(String value) {
            addCriterion("resource <=", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceLike(String value) {
            addCriterion("resource like", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotLike(String value) {
            addCriterion("resource not like", value, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceIn(List<String> values) {
            addCriterion("resource in", values, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotIn(List<String> values) {
            addCriterion("resource not in", values, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceBetween(String value1, String value2) {
            addCriterion("resource between", value1, value2, "resource");
            return (Criteria) this;
        }

        public Criteria andResourceNotBetween(String value1, String value2) {
            addCriterion("resource not between", value1, value2, "resource");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Integer value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Integer value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Integer value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Integer value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Integer value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Integer> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Integer> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Integer value1, Integer value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Double value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Double value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Double value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Double value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Double value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Double value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Double> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Double> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Double value1, Double value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Double value1, Double value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andStrategyIsNull() {
            addCriterion("strategy is null");
            return (Criteria) this;
        }

        public Criteria andStrategyIsNotNull() {
            addCriterion("strategy is not null");
            return (Criteria) this;
        }

        public Criteria andStrategyEqualTo(Integer value) {
            addCriterion("strategy =", value, "strategy");
            return (Criteria) this;
        }

        public Criteria andStrategyNotEqualTo(Integer value) {
            addCriterion("strategy <>", value, "strategy");
            return (Criteria) this;
        }

        public Criteria andStrategyGreaterThan(Integer value) {
            addCriterion("strategy >", value, "strategy");
            return (Criteria) this;
        }

        public Criteria andStrategyGreaterThanOrEqualTo(Integer value) {
            addCriterion("strategy >=", value, "strategy");
            return (Criteria) this;
        }

        public Criteria andStrategyLessThan(Integer value) {
            addCriterion("strategy <", value, "strategy");
            return (Criteria) this;
        }

        public Criteria andStrategyLessThanOrEqualTo(Integer value) {
            addCriterion("strategy <=", value, "strategy");
            return (Criteria) this;
        }

        public Criteria andStrategyIn(List<Integer> values) {
            addCriterion("strategy in", values, "strategy");
            return (Criteria) this;
        }

        public Criteria andStrategyNotIn(List<Integer> values) {
            addCriterion("strategy not in", values, "strategy");
            return (Criteria) this;
        }

        public Criteria andStrategyBetween(Integer value1, Integer value2) {
            addCriterion("strategy between", value1, value2, "strategy");
            return (Criteria) this;
        }

        public Criteria andStrategyNotBetween(Integer value1, Integer value2) {
            addCriterion("strategy not between", value1, value2, "strategy");
            return (Criteria) this;
        }

        public Criteria andRefResourceIsNull() {
            addCriterion("ref_resource is null");
            return (Criteria) this;
        }

        public Criteria andRefResourceIsNotNull() {
            addCriterion("ref_resource is not null");
            return (Criteria) this;
        }

        public Criteria andRefResourceEqualTo(String value) {
            addCriterion("ref_resource =", value, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceNotEqualTo(String value) {
            addCriterion("ref_resource <>", value, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceGreaterThan(String value) {
            addCriterion("ref_resource >", value, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceGreaterThanOrEqualTo(String value) {
            addCriterion("ref_resource >=", value, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceLessThan(String value) {
            addCriterion("ref_resource <", value, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceLessThanOrEqualTo(String value) {
            addCriterion("ref_resource <=", value, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceLike(String value) {
            addCriterion("ref_resource like", value, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceNotLike(String value) {
            addCriterion("ref_resource not like", value, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceIn(List<String> values) {
            addCriterion("ref_resource in", values, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceNotIn(List<String> values) {
            addCriterion("ref_resource not in", values, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceBetween(String value1, String value2) {
            addCriterion("ref_resource between", value1, value2, "refResource");
            return (Criteria) this;
        }

        public Criteria andRefResourceNotBetween(String value1, String value2) {
            addCriterion("ref_resource not between", value1, value2, "refResource");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorIsNull() {
            addCriterion("control_behavior is null");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorIsNotNull() {
            addCriterion("control_behavior is not null");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorEqualTo(Integer value) {
            addCriterion("control_behavior =", value, "controlBehavior");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorNotEqualTo(Integer value) {
            addCriterion("control_behavior <>", value, "controlBehavior");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorGreaterThan(Integer value) {
            addCriterion("control_behavior >", value, "controlBehavior");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorGreaterThanOrEqualTo(Integer value) {
            addCriterion("control_behavior >=", value, "controlBehavior");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorLessThan(Integer value) {
            addCriterion("control_behavior <", value, "controlBehavior");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorLessThanOrEqualTo(Integer value) {
            addCriterion("control_behavior <=", value, "controlBehavior");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorIn(List<Integer> values) {
            addCriterion("control_behavior in", values, "controlBehavior");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorNotIn(List<Integer> values) {
            addCriterion("control_behavior not in", values, "controlBehavior");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorBetween(Integer value1, Integer value2) {
            addCriterion("control_behavior between", value1, value2, "controlBehavior");
            return (Criteria) this;
        }

        public Criteria andControlBehaviorNotBetween(Integer value1, Integer value2) {
            addCriterion("control_behavior not between", value1, value2, "controlBehavior");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecIsNull() {
            addCriterion("warm_up_period_sec is null");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecIsNotNull() {
            addCriterion("warm_up_period_sec is not null");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecEqualTo(Integer value) {
            addCriterion("warm_up_period_sec =", value, "warmUpPeriodSec");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecNotEqualTo(Integer value) {
            addCriterion("warm_up_period_sec <>", value, "warmUpPeriodSec");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecGreaterThan(Integer value) {
            addCriterion("warm_up_period_sec >", value, "warmUpPeriodSec");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecGreaterThanOrEqualTo(Integer value) {
            addCriterion("warm_up_period_sec >=", value, "warmUpPeriodSec");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecLessThan(Integer value) {
            addCriterion("warm_up_period_sec <", value, "warmUpPeriodSec");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecLessThanOrEqualTo(Integer value) {
            addCriterion("warm_up_period_sec <=", value, "warmUpPeriodSec");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecIn(List<Integer> values) {
            addCriterion("warm_up_period_sec in", values, "warmUpPeriodSec");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecNotIn(List<Integer> values) {
            addCriterion("warm_up_period_sec not in", values, "warmUpPeriodSec");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecBetween(Integer value1, Integer value2) {
            addCriterion("warm_up_period_sec between", value1, value2, "warmUpPeriodSec");
            return (Criteria) this;
        }

        public Criteria andWarmUpPeriodSecNotBetween(Integer value1, Integer value2) {
            addCriterion("warm_up_period_sec not between", value1, value2, "warmUpPeriodSec");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsIsNull() {
            addCriterion("max_queueing_time_ms is null");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsIsNotNull() {
            addCriterion("max_queueing_time_ms is not null");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsEqualTo(Integer value) {
            addCriterion("max_queueing_time_ms =", value, "maxQueueingTimeMs");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsNotEqualTo(Integer value) {
            addCriterion("max_queueing_time_ms <>", value, "maxQueueingTimeMs");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsGreaterThan(Integer value) {
            addCriterion("max_queueing_time_ms >", value, "maxQueueingTimeMs");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_queueing_time_ms >=", value, "maxQueueingTimeMs");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsLessThan(Integer value) {
            addCriterion("max_queueing_time_ms <", value, "maxQueueingTimeMs");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsLessThanOrEqualTo(Integer value) {
            addCriterion("max_queueing_time_ms <=", value, "maxQueueingTimeMs");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsIn(List<Integer> values) {
            addCriterion("max_queueing_time_ms in", values, "maxQueueingTimeMs");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsNotIn(List<Integer> values) {
            addCriterion("max_queueing_time_ms not in", values, "maxQueueingTimeMs");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsBetween(Integer value1, Integer value2) {
            addCriterion("max_queueing_time_ms between", value1, value2, "maxQueueingTimeMs");
            return (Criteria) this;
        }

        public Criteria andMaxQueueingTimeMsNotBetween(Integer value1, Integer value2) {
            addCriterion("max_queueing_time_ms not between", value1, value2, "maxQueueingTimeMs");
            return (Criteria) this;
        }

        public Criteria andClustermodeIsNull() {
            addCriterion("clusterMode is null");
            return (Criteria) this;
        }

        public Criteria andClustermodeIsNotNull() {
            addCriterion("clusterMode is not null");
            return (Criteria) this;
        }

        public Criteria andClustermodeEqualTo(Byte value) {
            addCriterion("clusterMode =", value, "clustermode");
            return (Criteria) this;
        }

        public Criteria andClustermodeNotEqualTo(Byte value) {
            addCriterion("clusterMode <>", value, "clustermode");
            return (Criteria) this;
        }

        public Criteria andClustermodeGreaterThan(Byte value) {
            addCriterion("clusterMode >", value, "clustermode");
            return (Criteria) this;
        }

        public Criteria andClustermodeGreaterThanOrEqualTo(Byte value) {
            addCriterion("clusterMode >=", value, "clustermode");
            return (Criteria) this;
        }

        public Criteria andClustermodeLessThan(Byte value) {
            addCriterion("clusterMode <", value, "clustermode");
            return (Criteria) this;
        }

        public Criteria andClustermodeLessThanOrEqualTo(Byte value) {
            addCriterion("clusterMode <=", value, "clustermode");
            return (Criteria) this;
        }

        public Criteria andClustermodeIn(List<Byte> values) {
            addCriterion("clusterMode in", values, "clustermode");
            return (Criteria) this;
        }

        public Criteria andClustermodeNotIn(List<Byte> values) {
            addCriterion("clusterMode not in", values, "clustermode");
            return (Criteria) this;
        }

        public Criteria andClustermodeBetween(Byte value1, Byte value2) {
            addCriterion("clusterMode between", value1, value2, "clustermode");
            return (Criteria) this;
        }

        public Criteria andClustermodeNotBetween(Byte value1, Byte value2) {
            addCriterion("clusterMode not between", value1, value2, "clustermode");
            return (Criteria) this;
        }

        public Criteria andClusterConfigIsNull() {
            addCriterion("cluster_config is null");
            return (Criteria) this;
        }

        public Criteria andClusterConfigIsNotNull() {
            addCriterion("cluster_config is not null");
            return (Criteria) this;
        }

        public Criteria andClusterConfigEqualTo(String value) {
            addCriterion("cluster_config =", value, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigNotEqualTo(String value) {
            addCriterion("cluster_config <>", value, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigGreaterThan(String value) {
            addCriterion("cluster_config >", value, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigGreaterThanOrEqualTo(String value) {
            addCriterion("cluster_config >=", value, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigLessThan(String value) {
            addCriterion("cluster_config <", value, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigLessThanOrEqualTo(String value) {
            addCriterion("cluster_config <=", value, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigLike(String value) {
            addCriterion("cluster_config like", value, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigNotLike(String value) {
            addCriterion("cluster_config not like", value, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigIn(List<String> values) {
            addCriterion("cluster_config in", values, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigNotIn(List<String> values) {
            addCriterion("cluster_config not in", values, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigBetween(String value1, String value2) {
            addCriterion("cluster_config between", value1, value2, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andClusterConfigNotBetween(String value1, String value2) {
            addCriterion("cluster_config not between", value1, value2, "clusterConfig");
            return (Criteria) this;
        }

        public Criteria andFlowRuleIsNull() {
            addCriterion("flow_rule is null");
            return (Criteria) this;
        }

        public Criteria andFlowRuleIsNotNull() {
            addCriterion("flow_rule is not null");
            return (Criteria) this;
        }

        public Criteria andFlowRuleEqualTo(String value) {
            addCriterion("flow_rule =", value, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleNotEqualTo(String value) {
            addCriterion("flow_rule <>", value, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleGreaterThan(String value) {
            addCriterion("flow_rule >", value, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleGreaterThanOrEqualTo(String value) {
            addCriterion("flow_rule >=", value, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleLessThan(String value) {
            addCriterion("flow_rule <", value, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleLessThanOrEqualTo(String value) {
            addCriterion("flow_rule <=", value, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleLike(String value) {
            addCriterion("flow_rule like", value, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleNotLike(String value) {
            addCriterion("flow_rule not like", value, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleIn(List<String> values) {
            addCriterion("flow_rule in", values, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleNotIn(List<String> values) {
            addCriterion("flow_rule not in", values, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleBetween(String value1, String value2) {
            addCriterion("flow_rule between", value1, value2, "flowRule");
            return (Criteria) this;
        }

        public Criteria andFlowRuleNotBetween(String value1, String value2) {
            addCriterion("flow_rule not between", value1, value2, "flowRule");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNull() {
            addCriterion("oper_id is null");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNotNull() {
            addCriterion("oper_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperIdEqualTo(String value) {
            addCriterion("oper_id =", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotEqualTo(String value) {
            addCriterion("oper_id <>", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThan(String value) {
            addCriterion("oper_id >", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("oper_id >=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThan(String value) {
            addCriterion("oper_id <", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThanOrEqualTo(String value) {
            addCriterion("oper_id <=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLike(String value) {
            addCriterion("oper_id like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotLike(String value) {
            addCriterion("oper_id not like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdIn(List<String> values) {
            addCriterion("oper_id in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotIn(List<String> values) {
            addCriterion("oper_id not in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdBetween(String value1, String value2) {
            addCriterion("oper_id between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotBetween(String value1, String value2) {
            addCriterion("oper_id not between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table flow_rule
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 15 17:37:58 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}