package com.alibaba.csp.sentinel.dashboard.biz.entity;

import java.io.Serializable;
import java.util.Date;

public class ParamFlowRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_flow_rule.id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_flow_rule.app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String app;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_flow_rule.rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_flow_rule.param_flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String paramFlowRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_flow_rule.oper_id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_flow_rule.creator
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_flow_rule.gmt_create
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_flow_rule.gmt_modified
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table param_flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_flow_rule.id
     *
     * @return the value of param_flow_rule.id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_flow_rule.id
     *
     * @param id the value for param_flow_rule.id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_flow_rule.app
     *
     * @return the value of param_flow_rule.app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_flow_rule.app
     *
     * @param app the value for param_flow_rule.app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setApp(String app) {
        this.app = app == null ? null : app.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_flow_rule.rule
     *
     * @return the value of param_flow_rule.rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_flow_rule.rule
     *
     * @param rule the value for param_flow_rule.rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_flow_rule.param_flow_rule
     *
     * @return the value of param_flow_rule.param_flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getParamFlowRule() {
        return paramFlowRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_flow_rule.param_flow_rule
     *
     * @param paramFlowRule the value for param_flow_rule.param_flow_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setParamFlowRule(String paramFlowRule) {
        this.paramFlowRule = paramFlowRule == null ? null : paramFlowRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_flow_rule.oper_id
     *
     * @return the value of param_flow_rule.oper_id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_flow_rule.oper_id
     *
     * @param operId the value for param_flow_rule.oper_id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_flow_rule.creator
     *
     * @return the value of param_flow_rule.creator
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_flow_rule.creator
     *
     * @param creator the value for param_flow_rule.creator
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_flow_rule.gmt_create
     *
     * @return the value of param_flow_rule.gmt_create
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_flow_rule.gmt_create
     *
     * @param gmtCreate the value for param_flow_rule.gmt_create
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_flow_rule.gmt_modified
     *
     * @return the value of param_flow_rule.gmt_modified
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_flow_rule.gmt_modified
     *
     * @param gmtModified the value for param_flow_rule.gmt_modified
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}