package com.alibaba.csp.sentinel.dashboard.biz.entity;

import java.io.Serializable;
import java.util.Date;

public class SystemRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String app;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.highest_system_load
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Double highestSystemLoad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.avg_rt
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Long avgRt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.max_thread
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Long maxThread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.qps
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Double qps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.highest_cpu_usage
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Double highestCpuUsage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.system_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String systemRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.oper_id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.creator
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.gmt_create
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rule.gmt_modified
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.id
     *
     * @return the value of system_rule.id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.id
     *
     * @param id the value for system_rule.id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.app
     *
     * @return the value of system_rule.app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.app
     *
     * @param app the value for system_rule.app
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setApp(String app) {
        this.app = app == null ? null : app.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.highest_system_load
     *
     * @return the value of system_rule.highest_system_load
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Double getHighestSystemLoad() {
        return highestSystemLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.highest_system_load
     *
     * @param highestSystemLoad the value for system_rule.highest_system_load
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setHighestSystemLoad(Double highestSystemLoad) {
        this.highestSystemLoad = highestSystemLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.avg_rt
     *
     * @return the value of system_rule.avg_rt
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Long getAvgRt() {
        return avgRt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.avg_rt
     *
     * @param avgRt the value for system_rule.avg_rt
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setAvgRt(Long avgRt) {
        this.avgRt = avgRt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.max_thread
     *
     * @return the value of system_rule.max_thread
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Long getMaxThread() {
        return maxThread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.max_thread
     *
     * @param maxThread the value for system_rule.max_thread
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setMaxThread(Long maxThread) {
        this.maxThread = maxThread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.qps
     *
     * @return the value of system_rule.qps
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Double getQps() {
        return qps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.qps
     *
     * @param qps the value for system_rule.qps
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setQps(Double qps) {
        this.qps = qps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.highest_cpu_usage
     *
     * @return the value of system_rule.highest_cpu_usage
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Double getHighestCpuUsage() {
        return highestCpuUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.highest_cpu_usage
     *
     * @param highestCpuUsage the value for system_rule.highest_cpu_usage
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setHighestCpuUsage(Double highestCpuUsage) {
        this.highestCpuUsage = highestCpuUsage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.system_rule
     *
     * @return the value of system_rule.system_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getSystemRule() {
        return systemRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.system_rule
     *
     * @param systemRule the value for system_rule.system_rule
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setSystemRule(String systemRule) {
        this.systemRule = systemRule == null ? null : systemRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.oper_id
     *
     * @return the value of system_rule.oper_id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.oper_id
     *
     * @param operId the value for system_rule.oper_id
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.creator
     *
     * @return the value of system_rule.creator
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.creator
     *
     * @param creator the value for system_rule.creator
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.gmt_create
     *
     * @return the value of system_rule.gmt_create
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.gmt_create
     *
     * @param gmtCreate the value for system_rule.gmt_create
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rule.gmt_modified
     *
     * @return the value of system_rule.gmt_modified
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rule.gmt_modified
     *
     * @param gmtModified the value for system_rule.gmt_modified
     *
     * @mbggenerated Sat Apr 15 17:37:58 CST 2023
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}